apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: onb-us-steps-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onb-us-steps-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/steps_us
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /onboarding/steps_us
